-- in init.lua lazy setup under nvim_create_autocmd
-- OLD CONFIG PRE FORK SYNC
-- Create a command `:Format` local to the LSP buffer
-- vim.api.nvim_buf_create_user_command(bufnr, 'Format', function(_)
--   vim.lsp.buf.format()
-- end, { desc = 'Format current buffer with LSP' })